### ISSUE TITLE
[RN 0.44] Build failed: TouchEvent.obtain Arguments

### ISSUE THREAD

**Issue by spoeck** [react-native-community/react-native-svg#322]
``` 
node_modules\react-native-svg\android\src\main\java\com\horcrux\svg\SvgView.java:123: error: method obtain in class TouchEvent cannot be applied to given types;
            TouchEvent.obtain(
                      ^
  required: int,TouchEventType,MotionEvent,long,float,float,TouchEventCoalescingKeyHelper
  found: int,TouchEventType,MotionEvent,float,float,TouchEventCoalescingKeyHelper
  reason: actual and formal argument lists differ in length
1 error
:react-native-svg:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-svg:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by yangyi** [comment]
make a quick fix, not sure it will work correctly

https://github.com/yangyi/react-native-svg/commit/a265a2f4901597a709e01a45187731f10e10f50e

**Comment by magicismight** [comment]
I'll fix this later.

**Comment by willdawsonme** [comment]
For those wondering, it looks like this was fixed in https://github.com/react-native-community/react-native-svg/commit/2fd178da2872a169e13100308e0cff524197e26a and a new version published to npm (5.1.8). Is that right, @magicismight?

**Comment by kytwb** [comment]
@willdawsonme I still get this error on Windows with `react-native-svg#5.1.8`.

**Comment by fredjens** [comment]
This is still not fixed.
