### ISSUE TITLE
Crashing on Android

### ISSUE THREAD

**Issue by kevinejohn** [react-native-community/react-native-svg#38]
Anyone else experiencing crashing on Android?

Details here:
https://github.com/facebook/react-native/issues/6760

**Comment by magicismight** [comment]
I have no idea about what happened here.
And we are no longer depend on ReactNativeART anymore

**Comment by kevinejohn** [comment]
I tried both versions `react-native-svg` and `react-native-art-svg` and they both seem to crash on random intervals. I did notice it does not crash when I turn off debug mode. I still don't know why. I'll see if I can come up with an example project. I will post anything else I find.

**Comment by TRNIntegrations** [comment]
We're seeing this too, random crashes due to this package.

**Comment by laaxlabs** [comment]
+1

**Comment by dmkmedina** [comment]
I've run into the same issue with both packages. Interesting for me it doesn't crash when debugging in Chrome, but will consistently crash when it is not.

**Comment by esutton** [comment]
Clues are badly needed.

Has anyone posted the crash debug info needed to help trouble-shoot this?

I am afraid to invest time in using this component with this issue #38 active

**Comment by kevinejohn** [comment]
@esutton  Crash logs are posted here: https://github.com/facebook/react-native/issues/6760

**Comment by fab1an** [comment]
Some android phones crash on a reflection-exception with a `SIGSEGV` while others show it correctly.

So it may be that a call to `newInstance` somewhere is the culprit. Maybe https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManagerPropertyUpdater.java#L101.

`gson` suffered from this too: https://github.com/google/gson/issues/817

**Comment by SirCmpwn** [comment]
Can consistently reproduce with this app:

https://gogs.sr.ht/SirCmpwn/sotp

**Comment by JonathanKirknes** [comment]
I am also getting error on Android.

Here is the error report.
     
    Error while updating prop d
        java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Method.invoke(Native Method)
            at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:99)
            at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:150)
            at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:52)
            at com.facebook.react.uimanager.ReactShadowNode.updateProperties(ReactShadowNode.java:176)
            at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:163)
            at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:205)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
            at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:139)
            at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
            at android.os.Looper.loop(Looper.java:158)
            at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
            at java.lang.Thread.run(Thread.java:818)
         Caused by: com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `double', but had type `null'
            at com.facebook.react.bridge.ReadableNativeArray.getDouble(Native Method)
            at com.horcrux.svg.PropHelper.toFloatArray(PropHelper.java:54)
            at com.horcrux.svg.PropHelper.toFloatArray(PropHelper.java:35)
            at com.horcrux.svg.RNSVGPathShadowNode.setPath(RNSVGPathShadowNode.java:71)
            at java.lang.reflect.Method.invoke(Native Method) 
            at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:99) 
            at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:150) 
            at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:52) 
            at com.facebook.react.uimanager.ReactShadowNode.updateProperties(ReactShadowNode.java:176) 
            at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:163) 
            at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:205) 
            at java.lang.reflect.Method.invoke(Native Method) 
            at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319) 
            at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:139) 
            at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
            at android.os.Handler.handleCallback(Handler.java:739) 
            at android.os.Handler.dispatchMessage(Handler.java:95) 
            at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
            at android.os.Looper.loop(Looper.java:158) 
            at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
            at java.lang.Thread.run(Thread.java:818)

**Comment by ryd0rz** [comment]
This is also crashing for me on random intervals... crashing is increased when animating.

**Comment by ryd0rz** [comment]
Hey guys, if your not using a viewBox... consider using a viewBox... it may have fixed it for me... not seeing the crash anymore, and it was happening once every 15 loads approx.

**Comment by gpEscrivo** [comment]
Here is a stack trace from an android crash. Caused by setNativeProps of the transform of a <View>, surrounding an <Svg>, this error is intermittent, and only occurs occasionally: 

```
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RNSVGSvgView
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:88)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:121)
       at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:91)
       at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:782)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
       at com.facebook.react.uimanager.UIViewOperationQueue.pauseFrameCallback(UIViewOperationQueue.java:823)
       at com.facebook.react.uimanager.UIImplementation.onHostPause(UIImplementation.java:611)
       at com.facebook.react.uimanager.UIManagerModule.onHostPause(UIManagerModule.java:115)
       at com.facebook.react.bridge.ReactContext.onHostPause(ReactContext.java:179)
       at com.facebook.react.ReactInstanceManagerImpl.tearDownReactContext(ReactInstanceManagerImpl.java:794)
       at com.facebook.react.ReactInstanceManagerImpl.access$500(ReactInstanceManagerImpl.java:99)
       at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPreExecute(ReactInstanceManagerImpl.java:184)
       at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:604)
       at android.os.AsyncTask.execute(AsyncTask.java:551)
       at com.facebook.react.ReactInstanceManagerImpl.recreateReactContextInBackground(ReactInstanceManagerImpl.java:727)
       at com.facebook.react.ReactInstanceManagerImpl.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:710)
       at com.facebook.react.ReactInstanceManagerImpl.access$100(ReactInstanceManagerImpl.java:99)
       at com.facebook.react.ReactInstanceManagerImpl$1.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:138)
       at com.facebook.react.devsupport.DevSupportManagerImpl$18$1.run(DevSupportManagerImpl.java:673)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:77)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:121)
       at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:91)
       at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:782)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
       at com.facebook.react.uimanager.UIViewOperationQueue.pauseFrameCallback(UIViewOperationQueue.java:823)
       at com.facebook.react.uimanager.UIImplementation.onHostPause(UIImplementation.java:611)
       at com.facebook.react.uimanager.UIManagerModule.onHostPause(UIManagerModule.java:115)
       at com.facebook.react.bridge.ReactContext.onHostPause(ReactContext.java:179)
       at com.facebook.react.ReactInstanceManagerImpl.tearDownReactContext(ReactInstanceManagerImpl.java:794)
       at com.facebook.react.ReactInstanceManagerImpl.access$500(ReactInstanceManagerImpl.java:99)
       at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPreExecute(ReactInstanceManagerImpl.java:184)
       at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:604)
       at android.os.AsyncTask.execute(AsyncTask.java:551)
       at com.facebook.react.ReactInstanceManagerImpl.recreateReactContextInBackground(ReactInstanceManagerImpl.java:727)
       at com.facebook.react.ReactInstanceManagerImpl.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:710)
       at com.facebook.react.ReactInstanceManagerImpl.access$100(ReactInstanceManagerImpl.java:99)
       at com.facebook.react.ReactInstanceManagerImpl$1.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:138)
       at com.facebook.react.devsupport.DevSupportManagerImpl$18$1.run(DevSupportManagerImpl.java:673)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `double', but had type `object'
       at com.facebook.react.bridge.ReadableNativeArray.getDouble(ReadableNativeArray.java)
       at com.facebook.react.uimanager.BaseViewManager.setTransformMatrix(BaseViewManager.java:159)
       at com.facebook.react.uimanager.BaseViewManager.setTransform(BaseViewManager.java:58)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:77)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:121)
       at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:91)
       at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:782)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
       at com.facebook.react.uimanager.UIViewOperationQueue.pauseFrameCallback(UIViewOperationQueue.java:823)
       at com.facebook.react.uimanager.UIImplementation.onHostPause(UIImplementation.java:611)
       at com.facebook.react.uimanager.UIManagerModule.onHostPause(UIManagerModule.java:115)
       at com.facebook.react.bridge.ReactContext.onHostPause(ReactContext.java:179)
       at com.facebook.react.ReactInstanceManagerImpl.tearDownReactContext(ReactInstanceManagerImpl.java:794)
       at com.facebook.react.ReactInstanceManagerImpl.access$500(ReactInstanceManagerImpl.java:99)
       at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPreExecute(ReactInstanceManagerImpl.java:184)
       at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:604)
       at android.os.AsyncTask.execute(AsyncTask.java:551)
       at com.facebook.react.ReactInstanceManagerImpl.recreateReactContextInBackground(ReactInstanceManagerImpl.java:727)
       at com.facebook.react.ReactInstanceManagerImpl.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:710)
       at com.facebook.react.ReactInstanceManagerImpl.access$100(ReactInstanceManagerImpl.java:99)
       at com.facebook.react.ReactInstanceManagerImpl$1.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:138)
       at com.facebook.react.devsupport.DevSupportManagerImpl$18$1.run(DevSupportManagerImpl.java:673)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by ggsrivas** [comment]
Did anyone find any solution or workaround for this issue? I am also facing it.

**Comment by simzen85** [comment]
+1

**Comment by ggsrivas** [comment]
I could solve this problem for my use case. In my case, I changed my image component with,
shouldComponentUpdate() {
  return false;
}

and my app is not crashing now. I don't exactly know what was the root cause of this problem, but definitely my component didn't need to be re-rendered every time.

**Comment by dmkmedina** [comment]
@ggsrivas: This seems to work for me as well. Not sure if its a long term solution though.

**Comment by SirCmpwn** [comment]
>Not sure if its a long term solution though.

Indeed. I actually animate this component as a core part of my app's functionality.

**Comment by ggsrivas** [comment]
I agree. If you need animation then this solution will not work. Actually, in my application, I also have one svg image(loading spinner) which uses animation and my app is working without crash with this component. One way of finding out which element is causing crash is to remove svg elements one by one and see if your app is still crashing or not.

**Comment by fab1an** [comment]
The reason is because of this bug: https://github.com/facebook/fresco/issues/1363

Memory cleanup of animated images is broken in Fresco: https://github.com/facebook/fresco/issues/1363#issuecomment-233865933

**Comment by magicismight** [comment]
I'm not sure if [this ART commit](https://github.com/facebook/react-native/pull/9486) is related with this problem.
But I'll get this merged into react-native-svg see what would happen.

**Comment by dacarley** [comment]
@magicismight Have you made progress on this?  Our app (BlitzPick -- not yet available on Google Play, but it is available for iOS) uses react-native-svg for all of its icons, and we're having massive stability problems as we're trying to get it ready for public consumption.

**Comment by magicismight** [comment]
@dacarley  Sorry about that,I'll get that commit merged today.

**Comment by dacarley** [comment]
@magicismight Sorry to harp, but have you been able to get to this?

**Comment by magicismight** [comment]
I'm working on it, found it's not that easy to get that commit merged into svg.
It have to change the SvgView into a subclass from TextureView.
That introduces many new problems.

**Comment by magicismight** [comment]
We have changed the SvgView into a subclass from ViewGroup insteadof View for some reasons.
So that changes many things.

**Comment by mlabrum** [comment]
Hi @magicismight,
Is there any update on this?

Thanks!

**Comment by magicismight** [comment]
@mlabrum 
There are something went wrong with the Image, TouchEvents and onDataURL().
Maybe will be finished in 2 days.
But I cannot guarantee this.

**Comment by magicismight** [comment]
@dacarley DONE.
Released in react-native-svg@4.3.2
But I'm not sure if [this](https://github.com/facebook/react-native/issues/6760) has been fixed, can't find a way to test it.

**Comment by dacarley** [comment]
Thanks!  We’ll upgrade shortly.


On November 8, 2016 at 7:23:26 AM, Horcrux (notifications@github.com) wrote:

@dacarley <https://github.com/dacarley> DONE.
Released in react-native-svg@4.3.2
But I'm not sure if this
<https://github.com/facebook/react-native/issues/6760> has been fixed,
can't find a way to test it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/react-native-community/react-native-svg/issues/38#issuecomment-259165867>,
or mute the thread

**Comment by jevakallio** [comment]
@magicismight thank you for landing this change! Good news is, that our use case of `react-native-svg`, the app is now more stable  on version 4.3.2 and does not crash as often. The bad news is that it still crashes occasionally with the same error message as https://github.com/facebook/react-native/issues/6760
```
11-09 17:49:48.962  1515  1534 W WindowAnimator: Failed to dispatch window animation state change.
11-09 17:49:48.962  1515  1534 W WindowAnimator: android.os.DeadObjectException
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
11-09 17:49:48.962  1515  1534 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by avkvak** [comment]
Any news? It still crashes for me =(

**Comment by badaz** [comment]
+1

**Comment by JesseARWhite** [comment]
+1

This still crashes randomly in v 4.4.1 against React Native 0.39.2 for what appears to be the same reasons (Fatal signal 11 (SIGSEGV) at 0x67110038 (code=2)).  Much more likely to happen on views with significant SVG use.  For now I have had to remove a fair amount of SVGs in the view to get the app stable-ish.  I also noticed that the changes for 4.3.2 mentioned above by @magicismight  had been reverted, curious as to why?

FTR the crash goes away completely when when I remove all SVGs from views, until this bug is ironed out I won't be able to consider my app production ready as it makes it somewhat unstable and is now missing a fair amount of UI work.  This crash never happens on the apps iOS counterpart which shares most of the js code.

Just wanted to understand that if this is still a known issue that appears to be fixable?

**Comment by magicismight** [comment]
This is  still a known issue in ReactNativeART and react-native-svg.
I have no idea what's going wrong.
maybe it's the parsed path data send to JSBridge caused the problem.
I'll try to parse the `d` prop in native side and see what happened.

**Comment by magicismight** [comment]
Good news!
I have fixed this finally.
It's the JSBridge caused the crash.
The `d` prop in Path element is too large after serialized.
And I had moved the serialize part to java side, and it never throw `A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x9fa40028 in tid 4388 (mqt_js)` again.
I'll ship this fix in next version

**Comment by jevakallio** [comment]
@magicismight amazing! We'll test this ASAP.

**Comment by JesseARWhite** [comment]
Awesome thank you looking forward to checking it out!

- Jesse

**Comment by magicismight** [comment]
I have pushed the commits to a [new branch](https://github.com/react-native-community/react-native-svg/tree/path-native-parser).
Now just have finished the Android code and will finish the iOS code in maybe this weekend.

**Comment by SirCmpwn** [comment]
Thank you!

**Comment by magicismight** [comment]
4.6.0 has been released.
And I think it's time to close this issue now.
The crash caused by `A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0xxxxxxxx in tid xxxx (mqt_js)` has been fixed.
The crash caused by other errors should be posted in other issues.

**Comment by GrzegorzZajac000** [comment]
I updated react-native-svg to 4.6.0 and react-native to 0.40.0 and crashes are less frequently but problem still exists.
