### ISSUE TITLE
<Text> does not work in <G>

### ISSUE THREAD

**Issue by 031341403** [react-native-community/react-native-svg#568]
`<Svg
    height="100"
    width="200"
>
    <G
        rotate="50"
        origin="100, 50"
    >
        <Line
            x1="60"
            y1="10"
            x2="140"
            y2="10"
            stroke="#060"
        />

        <Rect
            x="60"
            y="20"
            height="50"
            width="80"
            stroke="#060"
            fill="#060"
        />

        <Text
            x="100"
            y="75"
            stroke="#600"
            fill="#600"
            textAnchor="middle"
        >
            Text grouped with shapes</Text>
    </G>
</Svg>`

I just run this test,  the first (<Line>) and the second(Rect) can work well, but the thrid（Text） don't show !

**Comment by mchen37** [comment]
Are you importing Text from react-native and react-native-svg perhaps? Normal React Text does not show up in Svg, only Svg.Text
```
import { Text } from 'react-native';
import Svg, { Text } from 'react-native-svg';
```

**Comment by Neha3011** [comment]
Hi, i am facing the same issue. 

my code is 

```
import React from 'react';
import { Path, Circle, Line, G, Text as SVGText } from 'react-native-svg'
<G key={index}>
              <Circle
                  style={{ zIndex: 10}}
                  cx={x(index)}
                  cy={y(value)}
                  r={4}
                  strokeWidth={2}
                  stroke={'#20AAC3'}
                  fill="white"
              />
              <Line
                  x1={x(index)}
                  y1={"250"}
                  x2={x(index)}
                  stroke="#BFE5EC"
                  strokeWidth="0.3"
              />
              <SVGText
                fontSize="20"
                fontWeight="bold"
                x={x(index)}
                y={"250"}
                textAnchor="middle"
              >Test</SVGText>
            </G>```

Test doesn't show

**Comment by Neha3011** [comment]
Adding the stack trace
```
Exponent[1228]: -[__NSArrayM floatValue]: unrecognized selector sent to instance 0x60000104e640
Exponent[1228]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM floatValue]: unrecognized selector sent to instance 0x60000104e640'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x000000010fca8b0b __exceptionPreprocess + 171
		1   libobjc.A.dylib                     0x000000010f071141 objc_exception_throw + 48
		2   CoreFoundation                      0x000000010fd18134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
		3   CoreFoundation                      0x000000010fc2f840 ___forwarding___ + 1024
		4   CoreFoundation                      0x000000010fc2f3b8 _CF_forwarding_prep_0 + 120
		5   Exponent                            0x000000010526dd81 +[ABI25_0_0RNSVGPercentageConverter stringToFloat:relative:offset:] + 130
		6   Exponent                            0x0000000105265b61 -[ABI25_0_0RNSVGGlyphContext pushContext:deltaX:deltaY:positionX:positionY:] + 150
		7   Exponent                            0x0000000105272ff6 -[ABI25_0_0RNSVGText pushGlyphContext] + 234
		8   Exponent                            0x0000000105272a92 -[ABI25_0_0RNSVGText getGroupPath:] + 36
		9   Exponent                            0x0000000105272906 -[ABI25_0_0RNSVGText renderLayerTo:] + 80
		10  Exponent                            0x000000010526f687 -[ABI25_0_0RNSVGRenderable renderTo:] + 166
		11  Exponent                            0x0000000105266b62 __37-[ABI25_0_0RNSVGGroup renderGroupTo:]_block_invoke + 178
```
 systemsoundserver-simd[1231]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
Exponent[1228]: -[__NSArrayM floatValue]: unrecognized selector sent to instance 0x60000104e640
Exponent[1228]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM floatValue]: unrecognized selector sent to instance 0x60000104e640'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x000000010fca8b0b __exceptionPreprocess + 171
		1   libobjc.A.dylib                     0x000000010f071141 objc_exception_throw + 48
		2   CoreFoundation                      0x000000010fd18134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
		3   CoreFoundation                      0x000000010fc2f840 ___forwarding___ + 1024
		4   CoreFoundation                      0x000000010fc2f3b8 _CF_forwarding_prep_0 + 120
		5   Exponent                            0x000000010526dd81 +[ABI25_0_0RNSVGPercentageConverter stringToFloat:relative:offset:] + 130
		6   Exponent                            0x0000000105265b61 -[ABI25_0_0RNSVGGlyphContext pushContext:deltaX:deltaY:positionX:positionY:] + 150
		7   Exponent                            0x0000000105272ff6 -[ABI25_0_0RNSVGText pushGlyphContext] + 234
		8   Exponent                            0x0000000105272a92 -[ABI25_0_0RNSVGText getGroupPath:] + 36
		9   Exponent                            0x0000000105272906 -[ABI25_0_0RNSVGText renderLayerTo:] + 80
		10  Exponent                            0x000000010526f687 -[ABI25_0_0RNSVGRenderable renderTo:] + 166
		11  Exponent                            0x0000000105266b62 __37-[ABI25_0_0RNSVGGroup renderGroupTo:]_block_invoke + 178
		12  Exponent                            0x0000000105269968 -[ABI25_0_0RNSVGNode traverseSubviews:] + 285
		13  Exponent                            0x0000000105266a86 -[ABI25_0_0RNSVGGroup renderGroupTo:] + 147
		14  Exponent                            0x000000010526f687 -[ABI25_0_0RNSVGRenderable renderTo:] + 166
		15  Exponent                            0x000000010527144b -[ABI25_0_0RNSVGSvgView drawRect:] + 1371
		16  UIKit                               0x000000010ccd4d45 -[UIView(CALayerDelegate) drawLayer:inContext:] + 489
		17  QuartzCore                          0x000000010c748500 -[CALayer drawInContext:] + 257
		18  QuartzCore                          0x000000010c65eae5 CABackingStoreUpdate_ + 2505
		19  QuartzCore                          0x000000010c7480fa ___ZN2CA5Layer8display_Ev_block_invoke + 61
		20  QuartzCore                          0x000000010c747df3 _ZN2CA5Layer8display_Ev + 1633
		21  QuartzCore                          0x000000010c73c31d _ZN2CA5Layer17display_if_neededEPNS_11TransactionE + 315
		22  QuartzCore                          0x000000010c73c3ab _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 35
		23  QuartzCore                          0x000000010c6cbe92 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 294
		24  QuartzCore                          0x000000010c6f8130 _ZN2CA11Transaction6commitEv + 468
		25  QuartzCore                          0x000000010c6f8b37 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 115
		26  CoreFoundation                      0x000000010fc4e717 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
		27  CoreFoundation                      0x000000010fc4e687 __CFRunLoopDoObservers + 391
		28  CoreFoundation                      0x000000010fc33720 __CFRunLoopRun + 1200
		29  CoreFoundation                      0x000000010fc33016 CFRunLoopRunSpecific + 406
		30  GraphicsServices                    0x00000001118eda24 GSEventRunModal + 62
		31  UIKit                               0x000000010cc12134 UIApplicationMain + 159
		32  Exponent                            0x0000000104796381 main + 80
		33  libdyld.dylib                       0x00000001108b465d start + 1
		34  ???                                 0x0000000000000001 0x0 + 1
	)
```

**Comment by ammichael** [comment]
I'm also having this issue. I can't render text inside Circle. And, yes, I'm importing from svg, not react-native.

Why is it closed?

**Comment by ap050492** [comment]
Same issue. Any Update ? @Neha3011 @msand @ammichael

**Comment by msand** [comment]
Are you using expo? It comes with a pre bundled version of react-native-svg and can't be combined with others.

**Comment by ap050492** [comment]
@msand Nop,i am not using expo

**Comment by msand** [comment]
Can you post a replication? I don't know how to make this issue appear

**Comment by mike-marcacci** [comment]
Is your Text component the one exported by react-native or react-native-svg?

**Comment by ninofiliu** [comment]
Same, `<Text>` seems to be having some issues.

`<G><Text>some text</Text></G>`: works fine

`<G><Text textAnchor="center">some text</Text></G>`: makes the whole app crash: no logged error, the app simply closes. It can be opened back but as soon as I navigate on the faulty component, it happens again. I have to delete the faulty tag, reinstall the app, and re-run `react-native run-android` to make it work again.

Weird and painful! Good luck on resolving the bug

---

Computer OS: Windows
Device OS: Android
Reproducible demo: Can't reproduce the fault on small bits of code

**Comment by mikeyyyzhao** [comment]
As updates on this? I'm running into this issue as well. My whole app crashes when I insert the code  into my svg

`<Text
        fontFamily="Raleway-Bold, Raleway"
        fontSize={12}
        fontWeight="bold"
        letterSpacing={1}
        fill="#FF1E4F"
        transform="translate(2240 -14246)"
      >
        <TSpan x={10} y={20}>
          {`15`}
        </TSpan>
      </Text>`

**Comment by msand** [comment]
Are you importing Text from react-native or from react-native-svg? Please provide a full replication.

**Comment by mikeyyyzhao** [comment]
I'm importing it from react-native-svg
`import React from "react";
import Svg, { G, Path, Text, TSpan } from "react-native-svg";
const SvgSketchSelectedSvg = props => (
  <Svg width={30} height={32} {...props}>
    <G fill="none" fillRule="evenodd">
      <Path
        d="M2243-14277.5c0 7.456 6.044 13.5 13.5 13.5s13.5-6.044 13.5-13.5c0-3.216-1.125-6.17-3.002-8.489a13.474 13.474 0 0 0-10.498-5.011h-12.077"
        stroke="#FF1D4F"
        strokeWidth={2}
      />
      <Path stroke="#FF1F50" fill="#FF1D4F" d="M2241-14289.5l5-4.5v9z" />
      <Text
        fontFamily="Raleway-Bold, Raleway"
        fontSize={12}
        fontWeight="bold"
        letterSpacing={1}
        fill="#FF1E4F"
        transform="translate(2240 -14295)"
      >
        <TSpan x={10} y={20}>
          {`15`}
        </TSpan>
      </Text>
    </G>
  </Svg>
);

export default SvgSketchSelectedSvg;

`

**Comment by mikeyyyzhao** [comment]
I'm updating it from react-native-svg. If I remove the Text part, the rest of the code runs no problem so I assume it's the Text component that causing the error. 

`import React from "react";

import Svg, { G, Path, Text, TSpan } from "react-native-svg";

const SvgSketchSelectedSvg = props => (

  <Svg width={30} height={32} {...props}>

    <G fill="none" fillRule="evenodd">

      <Path
        d="M2243-14277.5c0 7.456 6.044 13.5 13.5 13.5s13.5-6.044 13.5-13.5c0-3.216-1.125-6.17-3.002-8.489a13.474 13.474 0 0 0-10.498-5.011h-12.077"
        stroke="#FF1D4F"
        strokeWidth={2}
      />
      <Path stroke="#FF1F50" fill="#FF1D4F" d="M2241-14289.5l5-4.5v9z" />
      <Text
        fontFamily="Raleway-Bold, Raleway"
        fontSize={12}
        fontWeight="bold"
        letterSpacing={1}
        fill="#FF1E4F"
        transform="translate(2240 -14295)"
      >
        <TSpan x={10} y={20}>
          {`15`}
        </TSpan>
      </Text>
    </G>
  </Svg>
);

export default SvgSketchSelectedSvg;

`

Computer OS: Mac
Device OS: iOS
RN version: 0.57.1

**Comment by msand** [comment]
It seems you're missing a viewBox attribute, and apparently there's a bug with handling of letterSpacing as a number, giving it as a string works fine. Also, I would recommend to move the content to the origin, instead of having it offset to x=2240, and y=-14295, something like this:

```jsx
const SvgSketchSelectedSvg = props => (
  <Svg width={30} height={32} viewBox="0 0 40 42" {...props}>
    <G fill="none" fillRule="evenodd">
      <Path
        d="M3,17.5c0 7.456 6.044 13.5 13.5 13.5s13.5-6.044 13.5-13.5c0-3.216-1.125-6.17-3.002-8.489a13.474 13.474 0 0 0-10.498-5.011h-12.077"
        stroke="#FF1D4F"
        strokeWidth={2}
      />
      <Path stroke="#FF1F50" fill="#FF1D4F" d="M1,5.5l5-4.5v9z" />
      <Text
        fontFamily="Raleway-Bold, Raleway"
        fontSize={12}
        fontWeight="bold"
        letterSpacing="1"
        fill="#FF1E4F"
      >
        <TSpan x={10} y={20}>
          {`15`}
        </TSpan>
      </Text>
    </G>
  </Svg>
);

```

**Comment by msand** [comment]
@mikeyyyzhao I've fixed the crash with letterSpacing as numbers in c343229, can you test it?

```jsx
const SvgSketchSelectedSvg = props => (
  <Svg width={300} height={320} viewBox="0 0 32 32" {...props}>
    <G fill="none" fillRule="evenodd">
      <Path
        d="M3,17.5c0 7.456 6.044 13.5 13.5 13.5s13.5-6.044 13.5-13.5c0-3.216-1.125-6.17-3.002-8.489a13.474 13.474 0 0 0-10.498-5.011h-12.077"
        stroke="#FF1D4F"
        strokeWidth={2}
      />
      <Path stroke="#FF1F50" fill="#FF1D4F" d="M1,5.5l5-4.5v9z" />
      <Text
        fontFamily="Raleway-Bold, Raleway"
        fontSize={12}
        fontWeight="bold"
        letterSpacing={1}
        fill="#FF1E4F"
      >
        <TSpan x={10} y={20}>
          {`15`}
        </TSpan>
      </Text>
    </G>
  </Svg>
);
```

**Comment by mikeyyyzhao** [comment]
Hi @msand I tried the code and it still crashed. Here's the exact code that I ran:

`
import React, { Component } from 'react';

import { StyleSheet, View } from 'react-native';

import Svg, { G, Path, Text, TSpan } from 'react-native-svg';

const ForwardButton = props => (

  <Svg width={300} height={320} viewBox="0 0 32 32" {...props}>

    <G fill="none" fillRule="evenodd">
      <Path
        d="M3,17.5c0 7.456 6.044 13.5 13.5 13.5s13.5-6.044 13.5-13.5c0-3.216-1.125-6.17-3.002-8.489a13.474 13.474 0 0 0-10.498-5.011h-12.077"
        stroke="#FF1D4F"
        strokeWidth={2}
      />
      <Path stroke="#FF1F50" fill="#FF1D4F" d="M1,5.5l5-4.5v9z" />
      <Text
        fontFamily="Raleway-Bold, Raleway"
        fontSize={12}
        fontWeight="bold"
        letterSpacing={1}
        fill="#FF1E4F"
      >
        <TSpan x={10} y={20}>
          {`15`}
        </TSpan>
      </Text>
    </G>
  </Svg>

);

export default ForwardButton;

`

**Comment by msand** [comment]
Try changing letterSpacing={1} to letterSpacing="1"

**Comment by mikeyyyzhao** [comment]
It worked and didn't crash this time! Thanks for your help @msand!
