### ISSUE TITLE
[ios] OnPressOut fires instantly

### ISSUE THREAD

**Issue by EskelCz** [react-native-community/react-native-svg#713]
I ran into a problem with touch events on svg shapes.
When touched on a real ios phone OnPress**In** and OnPress**Out** events both fire instantly. OnPress mostly not at all.
I need there two events to be separated by users' intention. It works with mouse in ios simulator, and android works both simulated and on real device.

I suspect it has something to do with some micro movement which on ios screen happens constantly.
Can this be fixed to be consistent with android?
Thank you.

**Comment by haixoay96** [comment]
I also have same same proplem!

**Comment by kozillla** [comment]
I'm also experiencing the same issue. Interesting thing is that on older phones (iPhone 6) seems to be working fine , how ever on iPhone 7 plus and newer issue occurs.

**Comment by flogy** [comment]
I have this issue on a Samsung Galaxy S7 edge (SM-G935F) running Android 8.0.0 as well... Duration between onPressIn and onPressOut is between 10ms and 30ms most times...

**Comment by msand** [comment]
I think I have (gesture) interactions between native animated transforms and normal svg transforms working correctly now as well: https://github.com/react-native-community/react-native-svg/commit/8c05da043dea3f8d04420c2d7c9c11733e22258b

**Comment by msand** [comment]
@flogy Please open another issue for android with a full reproduction. This is probably resolved now. Comment or reopen otherwise.

**Comment by akepecs** [comment]
This problem is still occurring for me on an iPhone X (both physical device and the iOS simulator). The problem does not occur in the simulator using a iPhone SE (I don't have a physical iPhone SE to test on). 

I have noticed the problem while attempting to use victory native's tooltips on a VictoryBar chart.
I am using react-native-svg 8.0.10 and victory-native 31.0.0.

**Comment by msand** [comment]
@akepecs can you provide a repro? Either expo or something that can be cloned and run as is

**Comment by raphaelpinel** [comment]
I still had the issue that onPressOut fires immediately with Victory Pie on ios for iPhone 6S plus, 7, x (SE, 5S and 6 were fine), with victory-native 32.0.2, React Native 0.55.1 and react-native-svg 6.5.3.

I solved it in my code by replacing onPressOut with onResponderRelease.
onPressIn was fine. 
Maybe it can help someone?

**Comment by RAWLICK** [comment]
> I still had the issue that onPressOut fires immediately with Victory Pie on ios for iPhone 6S plus, 7, x (SE, 5S and 6 were fine), with victory-native 32.0.2, React Native 0.55.1 and react-native-svg 6.5.3.
> 
> I solved it in my code by replacing onPressOut with onResponderRelease. onPressIn was fine. Maybe it can help someone?

I am using react-native-svg: 15.12.1 version in my react-native: 0.77.3 version. I was getting same issue of onPressOut getting fired instantly on real Android Device. I used the OnResponderRelease parameter and it worked. I just want to know that is it truly a permanent safe alternative method?
