### ISSUE TITLE
Emoji disappearing in Text inside Group after translation

### ISSUE THREAD

**Issue by ankardon** [react-native-community/react-native-svg#927]
When you translate a Group containing a Text with an emoji, the emoji stops being rendered, while the remaining text will be displayed normally. This also happens when manipulating the x and y of the Group directly instead of using a transformation. Furthermore, without setting the backgroundColor of the surrounding View, the emoji won't be rendered at all.

App.js replicating the error:
```javascript
import React, {Component} from 'react';
import {View, TouchableOpacity} from 'react-native';
import {Svg, G, Text} from 'react-native-svg';

type Props = {};
export default class App extends Component<Props> {
constructor(props){
    super(props);
    this.state= {
 	i: 50
    }
}
  render() {
    return (
      <View style={{flex: 1, backgroundColor:"#fff"}} widht="100%" height="100%">
        <Svg
          ref="svg"
          height="80%"
          width="100%"
        >
          <G
            x={50}
            transform={`translate(${this.state.i},0)`}
            y={50}
          >
            <Text>Test 😀</Text>
          </G>
        </Svg>
        <TouchableOpacity style={
            {
              backgroundColor: "#f00",
              height: "20%",
              width: "100%",
            }
          }
          onPress={()=>{this.setState({i:this.state.i+1})}}/>
      </View>
    );
  }
}

```
Platform: Android 8.0.0

React-native info output:
```  React Native Environment Info:
    System:
      OS: Linux 4.13 Ubuntu 16.04.4 LTS (Xenial Xerus)
      CPU: (4) x64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
      Memory: 3.46 GB / 7.67 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.14.1 - /usr/bin/node
      npm: 6.4.1 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 19, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-28 | Intel x86 Atom_64
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.4 => 0.58.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by msand** [comment]
@ankardon I think I've fixed the issue. Can you try https://github.com/react-native-community/react-native-svg/commit/abb17bc7f0985c0b5eaa85ead7351e5c74a731f8

**Comment by ankardon** [comment]
@msand Thanks, it does work now! Mind that I am only able to test it on android.

**Comment by mjmasn** [comment]
@msand I'm still seeing this (or a similar issue) with a real Nexus 5X running Android 8.1.0.

For `<Text />` and `<TextPath />`, emojis don't render at all, sometimes one or all will show up briefly after a render (can't work out exactly why), but this is inside a pan/zoom component and as soon as the contents move due to the pan/zoom, the emojis disappear again :thinking:
